### ISSUE TITLE
Refactor export, add Subscriber and Publisher

### ISSUE THREAD

**Issue by mteodor** [mainflux/export#8]
Think about creating Subscriber interface that will be implemented using nats package, and Publisher interface that will be implemented using mqtt package. Then, you can use these interfaces from the service in order to read and forward messages. Also, maybe you can separate MQTT client and logger from Route in this way.

**Comment by drasko** [comment]
We already have Mainflux Publisher interface: https://github.com/mainflux/mainflux/blob/master/publisher.go

**Comment by mteodor** [comment]
Publisher is introduced while Subscriber not needed for now
